name: CI
on:
  repository_dispatch:
    types: [on-release]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: find assets
        shell: python
        run: |
          import json
          release = json.loads('''${{ toJSON(github.event.client_payload.release) }}''')
          macosAssets = [asset for asset in release['assets'] if '1' in asset['name']]
          print(macosAssets)
          open('${{ github.env }}', 'a').write(f"ASSET_URL={macosAssets[0]['browser_download_url']}\n")
      - name: compute hash
        run: |
          hash=$(curl -L "$ASSET_URL" | sha256sum)
          echo "hash = $hash"
          echo "$hash" > "asd-${{ toJSON(github.event.client_payload.release.tag_name) }}"

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "generated"
          git push
