name: CI
on:
  repository_dispatch:
    types: [on-release]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: find assets
        run: |
          import json
          release = json.loads('''${{ toJSON(github.event.client_payload.release) }}''')
          macosAssets = [asset['name'] for asset in release['assets']]
          print(macosAssets)
        shell: python
